"use client";

import { useRef, useState, useTransition } from "react";
import { FilePenLine, Loader2, Trash2, Upload } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { useRouter } from "next/navigation";
import { deleteCommercialGradeAction } from "@/features/commercial-grades/actions";
import { sendCommercialGradePdf } from "@/features/commercial-grades/upload-client";

export function ManageCommercialGradeButtons({ id, courseName }: { id: string; courseName: string }) {
  const [deleteOpen, setDeleteOpen] = useState(false); const [updateOpen, setUpdateOpen] = useState(false); const [confirm, setConfirm] = useState(""); const [pending, start] = useTransition(); const router = useRouter(); const updateForm = useRef<HTMLFormElement>(null);
  function remove() { start(async () => { try { const result = await deleteCommercialGradeAction({ id }); if (result.ok) { toast.success(result.message); setDeleteOpen(false); router.refresh(); } else toast.error(result.error); } catch { toast.error("Não foi possível excluir a grade. Verifique a conexão e tente novamente."); } }); }
  function update(data: FormData) { const file = data.get("file"); if (!(file instanceof File) || file.size === 0) return void toast.error("Selecione o PDF da nova versão."); start(async () => { const result = await sendCommercialGradePdf(`/api/commercial-grades/${id}/replace`, file); if (result.ok) { (/leitura simples/.test(result.message) ? toast.warning : toast.success)(result.message, { duration: 12_000 }); updateForm.current?.reset(); setUpdateOpen(false); router.refresh(); } else toast.error(result.error); }); }
  return <div className="flex flex-wrap gap-2 border-t pt-3"><Dialog open={updateOpen} onOpenChange={setUpdateOpen}><DialogTrigger asChild><Button size="sm" type="button" variant="outline"><FilePenLine className="size-3.5" /> Atualizar grade</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Atualizar {courseName}</DialogTitle><DialogDescription>Selecione a versão nova. A IA fará a leitura novamente e substituirá o PDF e as informações exibidas.</DialogDescription></DialogHeader><form ref={updateForm} action={update} className="space-y-4"><Input name="file" type="file" accept="application/pdf" required disabled={pending} /><DialogFooter><Button type="submit" disabled={pending}>{pending ? <Loader2 className="size-4 animate-spin" /> : <Upload className="size-4" />} {pending ? "Lendo a nova grade..." : "Atualizar e reler"}</Button></DialogFooter></form></DialogContent></Dialog><Button size="sm" type="button" variant="ghost" className="text-status-danger hover:text-status-danger" onClick={() => { setConfirm(""); setDeleteOpen(true); }}><Trash2 className="size-3.5" /> Excluir</Button><AlertDialog open={deleteOpen} onOpenChange={setDeleteOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir esta grade?</AlertDialogTitle><AlertDialogDescription>O PDF e suas informações comerciais serão removidos definitivamente. Para confirmar, digite <strong>EXCLUIR</strong>.</AlertDialogDescription></AlertDialogHeader><Input value={confirm} onChange={(event) => setConfirm(event.target.value)} placeholder="EXCLUIR" autoComplete="off" disabled={pending} /><AlertDialogFooter><AlertDialogCancel disabled={pending}>Cancelar</AlertDialogCancel><AlertDialogAction onClick={(event) => { event.preventDefault(); remove(); }} disabled={pending || confirm !== "EXCLUIR"} className="bg-destructive text-white hover:bg-destructive/90">{pending && <Loader2 className="size-4 animate-spin" />} Excluir definitivamente</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}
